server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/kitchen_service_db
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    user: postgres
    password: 0
    default-schema: public

  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topic:
        kitchen-order-status-updates: kitchen-order-status-updates-topic
      group:
        kitchen-status-group-id: kitchen-order-status-updates-group
    consumer:
      topic:
        order-creation: order-creation-topic
        waiter-order-status-updates: waiter-order-status-updates-topic
      group:
        waiter-status-group-id: waiter-order-status-updates-topic
        order-creation-group-id: order-creation-topic

  profiles:
    active: default

logging:
  level:
    liquibase: INFO

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.testcase.kitchenservice.entity

springdoc:
  api-docs:
    path: /api-docs

waiter-service:
  url: http://localhost:8080